name: Call Eclipse Dash License Scanner (Python)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  release:
    types: [published]

jobs:
  call-remote-dash-workflow:
    secrets: inherit
    uses: eclipse-xfsc/dev-ops/.github/workflows/eclipse-dash-licence-python.yml@main
    with:
      requirements_path: requirements.txt
